check admin user before release
git-svn-id: https://webcleaner.svn.sourceforge.net/svnroot/webcleaner/trunk/webcleaner2@3581 e058641e-7c0d-0410-ba67-d7ca6cf85b4a

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -73,8 +73,11 @@ md5sums:
 	(cd config && md5sum blacklists/{ads,aggressive,violence}/*.gz > extern-md5sums.txt)
 
 releasecheck:
-	@if grep xxxx ChangeLog; then \
+	@if grep xxxx ChangeLog > /dev/null; then \
 	  echo "Could not release: edit ChangeLog release date"; false; \
+	fi
+	@if ! grep 'adminuser="admin"' config/webcleaner.conf > /dev/null; then \
+	  echo "Could not release: add admin user to config"; false; \
 	fi
 
 release: releasecheck dist upload homepage
