fix bashims
git-svn-id: https://webcleaner.svn.sourceforge.net/svnroot/webcleaner/trunk/webcleaner2@5639 e058641e-7c0d-0410-ba67-d7ca6cf85b4a

diff --git a/debian/webcleaner.prerm b/debian/webcleaner.prerm
--- a/debian/webcleaner.prerm
+++ b/debian/webcleaner.prerm
@@ -3,7 +3,19 @@
 #
 # see: dh_installdeb(1)
 
-if [ "$1" = "remove" -o "$1" = "purge" ]; then
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+case "$1" in
+remove)
     # stop and exit service(s)
     webcleaner-ctl exit
     # remove service data
@@ -14,7 +26,14 @@ if [ "$1" = "remove" -o "$1" = "purge" ]; then
     rm -f /var/run/webcleaner.log/*
     # remove SSL certificates
     webcleaner-certificates remove
-fi
+    ;;
+failed-upgrade|upgrade|deconfigure)
+    ;;
+*)
+    echo "prerm called with unknown argument \`$1'" >&2
+    exit 1
+    ;;
+esac
 
 dpkg -L webcleaner |
 	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
